name: Deploy to digitalocean

on:
  push:
#    tags:
#    - stage-*
    branches:
    - master

jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - fullName: Checkout files
#        uses: actions/checkout@v2
#      - fullName: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#      - fullName: Build project with Maven
#        run: mvn clean package -DskipTests
#      - fullName: Copy Docker file
#        run: cp ${{ github.workspace }}/docker-deploy/Dockerfile ${{ github.workspace }}/Dockerfile
#      - fullName: Build and push Docker images
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          repository: augustomarco/nutricenter
#          tag_with_ref: true
#          tag_with_sha: true

  deploy:
#    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Get tag fullName
        uses: olegtarasov/get-tag@v2.1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get latest Docker image tag from Docker Hub
        id: docker_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/augustomarco/nutricenter/tags?page_size=1" | jq -r '.results[0].name')
          echo "Latest Docker tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      - name: Show LATEST Tag DockerHub
        run: |
          echo "Tag: $LATEST_TAG"

      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "$LATEST_TAG" --image docker-20-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait
