name: Staging to digitalocean

on:
  push:
    tags:
    - stage-*
    branches:
    - modulo5-gitHubActions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build project with Maven
        run: mvn clean package -DskipTests
      - name: Copy Docker file
        run: cp ${{ github.workspace }}/docker-deploy/Dockerfile ${{ github.workspace }}/Dockerfile
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: augustomarco/nutricenter
          tag_with_ref: true
          tag_with_sha: true

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "$GIT_TAG" --image docker-22-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait
