name: Docker build

on:
  push:
    branches: [ "modulo5-gitHubActions", "develop" ]
  pull_request:
    types: [opened, reopened]
    branches: [ "modulo5-gitHubActions", "develop" ]
jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Building the image from the Dockerfile
        uses: ./.github/action-docker
